copyright = "© Lian"
defaultContentLanguage = "zh"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Asia/Shanghai"
timeout = "120s"
title = "Gallery"

[params]
  defaultTheme = "dark"
  description = "Example site for hugo-theme-gallery"
  title = "Dark.Lotus.Gallery"
  [params.author]
    email = "lian@darklotus.cn"
    name = "Lian"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/dinglian1999"
    email = "mailto:lian@darklotus.cn"
    github = "https://github.com/lianlianlianlianlianlian"
    #youtube = "https://www.youtube.com/"
    website = "https://darklotus.cn"
    #mastodon = "https://darklotus.cn"
    #pixelfed = "https://darklotus.cn"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "Blog"
    url = "https://blog.darklotus.cn"
    weight = 3

[services]
  [services.rss]
    limit = 100
